### ISSUE TITLE
got error while issuing command $ clusterdock_ssh cdh machine-1.mycluster

### ISSUE THREAD

**Issue by ff-narendrak** [cloudera/clusterdock#33] opened 2017-11-26 20:34 UTC
I am running multi node cluster using below command and it is working fine. Through cloudera manager I am able to get see the services running 
$ clusterdock_run./bin/start_cluster-nmycluster cdh--primary-node=machine-1--secondary-nodes='machine-{2..4}'

But when I try to login using below command, I got error
$ clusterdock_ssh cdh machine-1.mycluster
clusterdock_ssh:32: = not found

**Comment by dimaspivak** [comment] 2017-11-26 20:37
Duplicate of #29.

**Closed by dimaspivak** 2017-11-26 20:37 UTC
